// =============================================
// place_image_overrides.js
// Карта картинок для достопримечательностей и красивых мест TravelPlan
//
// Как использовать:
// 1) Положи этот файл в js/place_image_overrides.js
// 2) Подключи его ПОСЛЕ js/utils.js в index.template.html / index.html:
//    <script src="js/place_image_overrides.js"></script>
// 3) В js/utils.js можно заменить блок TP_IMAGE_OVERRIDES.places на PLACE_IMAGE_OVERRIDES
//    или сделать: Object.assign(TP_IMAGE_OVERRIDES.places, PLACE_IMAGE_OVERRIDES);
// =============================================

const PLACE_IMAGE_OVERRIDES = {
'Алматы|Парк имени 28 гвардейцев-панфиловцев': 'assets/images/places/almaty-park-imeni-28-gvardeycev-panfilovcev.jpg',
    'Алматы|Вознесенский кафедральный собор': 'assets/images/places/almaty-voznesenskiy-kafedralnyy-sobor.jpg',
    'Алматы|Центральный государственный музей Казахстана': 'assets/images/places/almaty-centralnyy-gosudarstvennyy-muzey-kazahstana.jpg',
    'Алматы|Кок-Тобе': 'assets/images/places/almaty-kok-tobe.jpg',
    'Алматы|Большое Алматинское озеро': 'assets/images/places/almaty-bolshoe-almatinskoe-ozero.jpg',
    'Алматы|Чарынский каньон': 'assets/images/places/almaty-charynskiy-kanon.jpg',
    'Астана|Байтерек': 'assets/images/places/astana-bayterek.jpg',
    'Астана|Мечеть Хазрет Султан': 'assets/images/places/astana-mechet-hazret-sultan.jpg',
    'Астана|Национальный музей Республики Казахстан': 'assets/images/places/astana-nacionalnyy-muzey-respubliki-kazahstan.jpg',
    'Астана|Набережная реки Есиль': 'assets/images/places/astana-naberezhnaya-reki-esil.jpg',
    'Астана|Ботанический сад Астаны': 'assets/images/places/astana-botanicheskiy-sad-astany.jpg',
    'Астана|Парк Жетысу': 'assets/images/places/astana-park-zhetysu.jpg',
    'Шымкент|Цитадель Шымкента': 'assets/images/places/shymkent-citadel-shymkenta.jpg',
    'Шымкент|Парк Абая': 'assets/images/places/shymkent-park-abaya.jpg',
    'Шымкент|Этнопарк Кен-Баба': 'assets/images/places/shymkent-etnopark-ken-baba.jpg',
    'Шымкент|Сайрам-Угамский национальный парк': 'assets/images/places/shymkent-sayram-ugamskiy-nacionalnyy-park.jpg',
    'Шымкент|Аксу-Жабаглы': 'assets/images/places/shymkent-aksu-zhabagly.jpg',
    'Шымкент|Каньон Аксу': 'assets/images/places/shymkent-kanon-aksu.jpg',
    'Актау|Набережная Актау': 'assets/images/places/aktau-naberezhnaya-aktau.jpg',
    'Актау|Подземная мечеть Бекет-Ата': 'assets/images/places/aktau-podzemnaya-mechet-beket-ata.jpg',
    'Актау|Маяк на крыше жилого дома': 'assets/images/places/aktau-mayak-na-kryshe-zhilogo-doma.jpg',
    'Актау|Скальная тропа': 'assets/images/places/aktau-skalnaya-tropa.jpg',
    'Актау|Долина шаров Торыш': 'assets/images/places/aktau-dolina-sharov-torysh.jpg',
    'Актау|Голубая бухта': 'assets/images/places/aktau-golubaya-buhta.jpg',
    'Туркестан|Мавзолей Ходжи Ахмеда Ясави': 'assets/images/places/turkestan-mavzoley-hodzhi-ahmeda-yasavi.jpg',
    'Туркестан|Караван-сарай Turkistan': 'assets/images/places/turkestan-karavan-saray-turkistan.jpg',
    'Туркестан|Мавзолей Рабии Султан Бегим': 'assets/images/places/turkestan-mavzoley-rabii-sultan-begim.jpg',
    'Туркестан|Оазис Караван-сарая вечером': 'assets/images/places/turkestan-oazis-karavan-saraya-vecherom.jpg',
    'Туркестан|Сауран': 'assets/images/places/turkestan-sauran.jpg',
    'Туркестан|Окрестности Отрара': 'assets/images/places/turkestan-okrestnosti-otrara.jpg',
    'Бурабай|Поляна Абылай хана': 'assets/images/places/burabay-polyana-abylay-hana.jpg',
    'Бурабай|Музей природы Бурабая': 'assets/images/places/burabay-muzey-prirody-burabaya.jpg',
    'Бурабай|Кенесары үңгірі': 'assets/images/places/burabay-kenesary-g-r.jpg',
    'Бурабай|Озеро Бурабай': 'assets/images/places/burabay-ozero-burabay.jpg',
    'Бурабай|Скала Жумбактас': 'assets/images/places/burabay-skala-zhumbaktas.jpg',
    'Бурабай|Гора Окжетпес': 'assets/images/places/burabay-gora-okzhetpes.jpg',
    'Москва|Красная площадь': 'assets/images/places/moskva-krasnaya-ploschad.jpg',
    'Москва|Московский Кремль': 'assets/images/places/moskva-moskovskiy-kreml.jpg',
    'Москва|Государственная Третьяковская галерея': 'assets/images/places/moskva-gosudarstvennaya-tretyakovskaya-galereya.jpg',
    'Москва|Парк Зарядье': 'assets/images/places/moskva-park-zaryade.jpg',
    'Москва|Воробьёвы горы': 'assets/images/places/moskva-vorobevy-gory.jpg',
    'Москва|Патриаршие пруды': 'assets/images/places/moskva-patriarshie-prudy.jpg',
    'Санкт-Петербург|Эрмитаж': 'assets/images/places/sankt-peterburg-ermitazh.jpg',
    'Санкт-Петербург|Исаакиевский собор': 'assets/images/places/sankt-peterburg-isaakievskiy-sobor.jpg',
    'Санкт-Петербург|Петропавловская крепость': 'assets/images/places/sankt-peterburg-petropavlovskaya-krepost.jpg',
    'Санкт-Петербург|Дворцовая набережная': 'assets/images/places/sankt-peterburg-dvorcovaya-naberezhnaya.jpg',
    'Санкт-Петербург|Петергофские фонтаны': 'assets/images/places/sankt-peterburg-petergofskie-fontany.jpg',
    'Санкт-Петербург|Елагин остров': 'assets/images/places/sankt-peterburg-elagin-ostrov.jpg',
    'Сочи|Дендрарий Сочи': 'assets/images/places/sochi-dendrariy-sochi.jpg',
    'Сочи|Олимпийский парк': 'assets/images/places/sochi-olimpiyskiy-park.jpg',
    'Сочи|Морской вокзал Сочи': 'assets/images/places/sochi-morskoy-vokzal-sochi.jpg',
    'Сочи|Роза Хутор': 'assets/images/places/sochi-roza-hutor.jpg',
    'Сочи|Агурские водопады': 'assets/images/places/sochi-agurskie-vodopady.jpg',
    'Сочи|Тисо-самшитовая роща': 'assets/images/places/sochi-tiso-samshitovaya-roscha.jpg',
    'Казань|Казанский Кремль': 'assets/images/places/kazan-kazanskiy-kreml.jpg',
    'Казань|Мечеть Кул-Шариф': 'assets/images/places/kazan-mechet-kul-sharif.jpg',
    'Казань|Дворец земледельцев': 'assets/images/places/kazan-dvorec-zemledelcev.jpg',
    'Казань|Кремлёвская набережная': 'assets/images/places/kazan-kremlevskaya-naberezhnaya.jpg',
    'Казань|Озеро Кабан': 'assets/images/places/kazan-ozero-kaban.jpg',
    'Казань|Остров-град Свияжск': 'assets/images/places/kazan-ostrov-grad-sviyazhsk.jpg',
    'Калининград|Кафедральный собор': 'assets/images/places/kaliningrad-kafedralnyy-sobor.jpg',
    'Калининград|Музей янтаря': 'assets/images/places/kaliningrad-muzey-yantarya.jpg',
    'Калининград|Рыбная деревня': 'assets/images/places/kaliningrad-rybnaya-derevnya.jpg',
    'Калининград|Куршская коса': 'assets/images/places/kaliningrad-kurshskaya-kosa.jpg',
    'Калининград|Балтийская коса': 'assets/images/places/kaliningrad-baltiyskaya-kosa.jpg',
    'Калининград|Озеро Верхнее': 'assets/images/places/kaliningrad-ozero-verhnee.jpg',
    'Ларнака|Церковь Святого Лазаря': 'assets/images/places/larnaca-cerkov-svyatogo-lazarya.jpg',
    'Ларнака|Форт Ларнаки': 'assets/images/places/larnaca-fort-larnaki.jpg',
    'Ларнака|Акведук Камарес': 'assets/images/places/larnaca-akveduk-kamares.jpg',
    'Ларнака|Солёное озеро Ларнаки': 'assets/images/places/larnaca-solenoe-ozero-larnaki.jpg',
    'Ларнака|Пляж Финикудес': 'assets/images/places/larnaca-plyazh-finikudes.jpg',
    'Ларнака|Пляж Маккензи': 'assets/images/places/larnaca-plyazh-makkenzi.jpg',
    'Пафос|Археологический парк Пафоса': 'assets/images/places/paphos-arheologicheskiy-park-pafosa.jpg',
    'Пафос|Гробницы королей': 'assets/images/places/paphos-grobnicy-koroley.jpg',
    'Пафос|Замок Пафоса': 'assets/images/places/paphos-zamok-pafosa.jpg',
    'Пафос|Камень Афродиты': 'assets/images/places/paphos-kamen-afrodity.jpg',
    'Пафос|Голубая лагуна Акамаса': 'assets/images/places/paphos-golubaya-laguna-akamasa.jpg',
    'Пафос|Корал Бэй': 'assets/images/places/paphos-koral-bey.jpg',
    'Лимассол|Лимассольский замок': 'assets/images/places/limassol-limassolskiy-zamok.jpg',
    'Лимассол|Марина Лимассола': 'assets/images/places/limassol-marina-limassola.jpg',
    'Лимассол|Древний Курион': 'assets/images/places/limassol-drevniy-kurion.jpg',
    'Лимассол|Пляж Дасуди': 'assets/images/places/limassol-plyazh-dasudi.jpg',
    'Лимассол|Белые скалы Governor’s Beach': 'assets/images/places/limassol-belye-skaly-governor-s-beach.jpg',
    'Лимассол|Набережная Molos': 'assets/images/places/limassol-naberezhnaya-molos.jpg',
    'Никосия|Улица Ледра': 'assets/images/places/nicosia-ulica-ledra.jpg',
    'Никосия|Кипрский музей': 'assets/images/places/nicosia-kiprskiy-muzey.jpg',
    'Никосия|Венецианские стены Никосии': 'assets/images/places/nicosia-venecianskie-steny-nikosii.jpg',
    'Никосия|Старый город Никосии': 'assets/images/places/nicosia-staryy-gorod-nikosii.jpg',
    'Никосия|Парк Аталасса': 'assets/images/places/nicosia-park-atalassa.jpg',
    'Никосия|Пешеходные кварталы Лаики Гитонья': 'assets/images/places/nicosia-peshehodnye-kvartaly-laiki-gitonya.jpg',
    'Айя-Напа|Монастырь Айя-Напы': 'assets/images/places/ayya-napa-monastyr-ayya-napy.jpg',
    'Айя-Напа|Музей моря Thalassa': 'assets/images/places/ayya-napa-muzey-morya-thalassa.jpg',
    'Айя-Напа|Парк скульптур Айя-Напы': 'assets/images/places/ayya-napa-park-skulptur-ayya-napy.jpg',
    'Айя-Напа|Nissi Beach': 'assets/images/places/ayya-napa-nissi-beach.jpg',
    'Айя-Напа|Cape Greco': 'assets/images/places/ayya-napa-cape-greco.jpg',
    'Айя-Напа|Sea Caves': 'assets/images/places/ayya-napa-sea-caves.jpg',
    'Стамбул|Айя-София': 'assets/images/places/istanbul-ayya-sofiya.jpg',
    'Стамбул|Голубая мечеть': 'assets/images/places/istanbul-golubaya-mechet.jpg',
    'Стамбул|Дворец Топкапы': 'assets/images/places/istanbul-dvorec-topkapy.jpg',
    'Стамбул|Босфор на закате': 'assets/images/places/istanbul-bosfor-na-zakate.jpg',
    'Стамбул|Район Балат': 'assets/images/places/istanbul-rayon-balat.jpg',
    'Стамбул|Парк Эмирган': 'assets/images/places/istanbul-park-emirgan.jpg',
    'Анталья|Старый город Калеичи': 'assets/images/places/antalya-staryy-gorod-kaleichi.jpg',
    'Анталья|Ворота Адриана': 'assets/images/places/antalya-vorota-adriana.jpg',
    'Анталья|Музей Антальи': 'assets/images/places/antalya-muzey-antali.jpg',
    'Анталья|Водопады Дюден': 'assets/images/places/antalya-vodopady-dyuden.jpg',
    'Анталья|Пляж Коньяалты': 'assets/images/places/antalya-plyazh-konyaalty.jpg',
    'Анталья|Каньон Кёпрюлю': 'assets/images/places/antalya-kanon-kepryulyu.jpg',
    'Каппадокия|Музей под открытым небом Гёреме': 'assets/images/places/cappadocia-muzey-pod-otkrytym-nebom-gereme.jpg',
    'Каппадокия|Подземный город Деринкую': 'assets/images/places/cappadocia-podzemnyy-gorod-derinkuyu.jpg',
    'Каппадокия|Крепость Учхисар': 'assets/images/places/cappadocia-krepost-uchhisar.jpg',
    'Каппадокия|Долина Любви': 'assets/images/places/cappadocia-dolina-lyubvi.jpg',
    'Каппадокия|Долина Пашабаг': 'assets/images/places/cappadocia-dolina-pashabag.jpg',
    'Каппадокия|Полёт воздушных шаров над Гёреме': 'assets/images/places/cappadocia-polet-vozdushnyh-sharov-nad-gereme.jpg',
    'Измир|Часовая башня Измира': 'assets/images/places/izmir-chasovaya-bashnya-izmira.jpg',
    'Измир|Агора Смирны': 'assets/images/places/izmir-agora-smirny.jpg',
    'Измир|Рынок Кемералты': 'assets/images/places/izmir-rynok-kemeralty.jpg',
    'Измир|Набережная Кордон': 'assets/images/places/izmir-naberezhnaya-kordon.jpg',
    'Измир|Чешме': 'assets/images/places/izmir-cheshme.jpg',
    'Измир|Алачаты': 'assets/images/places/izmir-alachaty.jpg',
    'Дубай|Бурдж-Халифа': 'assets/images/places/dubai-burdzh-halifa.jpg',
    'Дубай|Dubai Mall': 'assets/images/places/dubai-dubai-mall.jpg',
    'Дубай|Музей будущего': 'assets/images/places/dubai-muzey-buduschego.jpg',
    'Дубай|Dubai Marina': 'assets/images/places/dubai-dubai-marina.jpg',
    'Дубай|Пляж JBR': 'assets/images/places/dubai-plyazh-jbr.jpg',
    'Дубай|Пустыня Аль-Мармум': 'assets/images/places/dubai-pustynya-al-marmum.jpg',
    'Абу-Даби|Мечеть шейха Зайда': 'assets/images/places/abu-dhabi-mechet-sheyha-zayda.jpg',
    'Абу-Даби|Лувр Абу-Даби': 'assets/images/places/abu-dhabi-luvr-abu-dabi.jpg',
    'Абу-Даби|Qasr Al Watan': 'assets/images/places/abu-dhabi-qasr-al-watan.jpg',
    'Абу-Даби|Corniche Beach': 'assets/images/places/abu-dhabi-corniche-beach.jpg',
    'Абу-Даби|Остров Саадият': 'assets/images/places/abu-dhabi-ostrov-saadiyat.jpg',
    'Абу-Даби|Мангровый парк Jubail': 'assets/images/places/abu-dhabi-mangrovyy-park-jubail.jpg',
    'Шарджа|Музей исламской цивилизации': 'assets/images/places/sharjah-muzey-islamskoy-civilizacii.jpg',
    'Шарджа|Blue Souk': 'assets/images/places/sharjah-blue-souk.jpg',
    'Шарджа|Sharjah Heritage Area': 'assets/images/places/sharjah-sharjah-heritage-area.jpg',
    'Шарджа|Al Noor Island': 'assets/images/places/sharjah-al-noor-island.jpg',
    'Шарджа|Al Majaz Waterfront': 'assets/images/places/sharjah-al-majaz-waterfront.jpg',
    'Шарджа|Пляж Аль-Хан': 'assets/images/places/sharjah-plyazh-al-han.jpg',
    'Тбилиси|Крепость Нарикала': 'assets/images/places/tbilisi-krepost-narikala.jpg',
    'Тбилиси|Старый Тбилиси': 'assets/images/places/tbilisi-staryy-tbilisi.jpg',
    'Тбилиси|Серные бани Абанотубани': 'assets/images/places/tbilisi-sernye-bani-abanotubani.jpg',
    'Тбилиси|Мтацминда': 'assets/images/places/tbilisi-mtacminda.jpg',
    'Тбилиси|Мост Мира вечером': 'assets/images/places/tbilisi-most-mira-vecherom.jpg',
    'Тбилиси|Черепашье озеро': 'assets/images/places/tbilisi-cherepashe-ozero.jpg',
    'Батуми|Батумский бульвар': 'assets/images/places/batumi-batumskiy-bulvar.jpg',
    'Батуми|Статуя Али и Нино': 'assets/images/places/batumi-statuya-ali-i-nino.jpg',
    'Батуми|Площадь Европы': 'assets/images/places/batumi-ploschad-evropy.jpg',
    'Батуми|Ботанический сад Батуми': 'assets/images/places/batumi-botanicheskiy-sad-batumi.jpg',
    'Батуми|Зелёный мыс': 'assets/images/places/batumi-zelenyy-mys.jpg',
    'Батуми|Водопад Махунцети': 'assets/images/places/batumi-vodopad-mahunceti.jpg',
    'Кутаиси|Храм Баграта': 'assets/images/places/kutaisi-hram-bagrata.jpg',
    'Кутаиси|Гелатский монастырь': 'assets/images/places/kutaisi-gelatskiy-monastyr.jpg',
    'Кутаиси|Белый мост': 'assets/images/places/kutaisi-belyy-most.jpg',
    'Кутаиси|Пещера Прометея': 'assets/images/places/kutaisi-peschera-prometeya.jpg',
    'Кутаиси|Каньон Мартвили': 'assets/images/places/kutaisi-kanon-martvili.jpg',
    'Кутаиси|Заповедник Сатаплия': 'assets/images/places/kutaisi-zapovednik-satapliya.jpg',
    'Прага|Пражский Град': 'assets/images/places/prague-prazhskiy-grad.jpg',
    'Прага|Карлов мост': 'assets/images/places/prague-karlov-most.jpg',
    'Прага|Староместская площадь': 'assets/images/places/prague-staromestskaya-ploschad.jpg',
    'Прага|Петршинский холм': 'assets/images/places/prague-petrshinskiy-holm.jpg',
    'Прага|Набережная Влтавы': 'assets/images/places/prague-naberezhnaya-vltavy.jpg',
    'Прага|Летенские сады': 'assets/images/places/prague-letenskie-sady.jpg',
    'Карловы Вары|Мельничная колоннада': 'assets/images/places/karlovy-vary-melnichnaya-kolonnada.jpg',
    'Карловы Вары|Гейзерная колоннада': 'assets/images/places/karlovy-vary-geyzernaya-kolonnada.jpg',
    'Карловы Вары|Музей Becherovka': 'assets/images/places/karlovy-vary-muzey-becherovka.jpg',
    'Карловы Вары|Смотровая Диана': 'assets/images/places/karlovy-vary-smotrovaya-diana.jpg',
    'Карловы Вары|Река Тепла': 'assets/images/places/karlovy-vary-reka-tepla.jpg',
    'Карловы Вары|Лесные прогулочные тропы': 'assets/images/places/karlovy-vary-lesnye-progulochnye-tropy.jpg',
    'Брно|Замок Шпильберк': 'assets/images/places/brno-zamok-shpilberk.jpg',
    'Брно|Собор Святых Петра и Павла': 'assets/images/places/brno-sobor-svyatyh-petra-i-pavla.jpg',
    'Брно|Вилла Тугендхат': 'assets/images/places/brno-villa-tugendhat.jpg',
    'Брно|Моравский карст': 'assets/images/places/brno-moravskiy-karst.jpg',
    'Брно|Плотина Брно': 'assets/images/places/brno-plotina-brno.jpg',
    'Брно|Парк Лужанки': 'assets/images/places/brno-park-luzhanki.jpg',
    'Барселона|Саграда Фамилия': 'assets/images/places/barcelona-sagrada-familiya.jpg',
    'Барселона|Парк Гуэль': 'assets/images/places/barcelona-park-guel.jpg',
    'Барселона|Дом Бальо': 'assets/images/places/barcelona-dom-balo.jpg',
    'Барселона|Пляж Барселонета': 'assets/images/places/barcelona-plyazh-barseloneta.jpg',
    'Барселона|Гора Монжуик': 'assets/images/places/barcelona-gora-monzhuik.jpg',
    'Барселона|Бункеры Carmel': 'assets/images/places/barcelona-bunkery-carmel.jpg',
    'Мадрид|Музей Прадо': 'assets/images/places/madrid-muzey-prado.jpg',
    'Мадрид|Королевский дворец Мадрида': 'assets/images/places/madrid-korolevskiy-dvorec-madrida.jpg',
    'Мадрид|Площадь Майор': 'assets/images/places/madrid-ploschad-mayor.jpg',
    'Мадрид|Парк Ретиро': 'assets/images/places/madrid-park-retiro.jpg',
    'Мадрид|Храм Дебод на закате': 'assets/images/places/madrid-hram-debod-na-zakate.jpg',
    'Мадрид|Сады Сабатини': 'assets/images/places/madrid-sady-sabatini.jpg',
    'Валенсия|Город искусств и наук': 'assets/images/places/valencia-gorod-iskusstv-i-nauk.jpg',
    'Валенсия|Кафедральный собор Валенсии': 'assets/images/places/valencia-kafedralnyy-sobor-valensii.jpg',
    'Валенсия|Центральный рынок': 'assets/images/places/valencia-centralnyy-rynok.jpg',
    'Валенсия|Парк Турия': 'assets/images/places/valencia-park-turiya.jpg',
    'Валенсия|Пляж Мальварроса': 'assets/images/places/valencia-plyazh-malvarrosa.jpg',
    'Валенсия|Альбуфера': 'assets/images/places/valencia-albufera.jpg',
    'Севилья|Севильский Алькасар': 'assets/images/places/seville-sevilskiy-alkasar.jpg',
    'Севилья|Севильский кафедральный собор': 'assets/images/places/seville-sevilskiy-kafedralnyy-sobor.jpg',
    'Севилья|Площадь Испании': 'assets/images/places/seville-ploschad-ispanii.jpg',
    'Севилья|Район Санта-Крус': 'assets/images/places/seville-rayon-santa-krus.jpg',
    'Севилья|Парк Марии-Луизы': 'assets/images/places/seville-park-marii-luizy.jpg',
    'Севилья|Набережная Гвадалквивира': 'assets/images/places/seville-naberezhnaya-gvadalkvivira.jpg',
    'Майорка|Кафедральный собор Пальмы': 'assets/images/places/mallorca-kafedralnyy-sobor-palmy.jpg',
    'Майорка|Замок Бельвер': 'assets/images/places/mallorca-zamok-belver.jpg',
    'Майорка|Старинный поезд Сольер': 'assets/images/places/mallorca-starinnyy-poezd-soler.jpg',
    'Майорка|Мыс Форментор': 'assets/images/places/mallorca-mys-formentor.jpg',
    'Майорка|Бухта Са Калобра': 'assets/images/places/mallorca-buhta-sa-kalobra.jpg',
    'Майорка|Пляж Эс-Тренк': 'assets/images/places/mallorca-plyazh-es-trenk.jpg',
    'Рим|Колизей': 'assets/images/places/rome-kolizey.jpg',
    'Рим|Римский форум': 'assets/images/places/rome-rimskiy-forum.jpg',
    'Рим|Пантеон': 'assets/images/places/rome-panteon.jpg',
    'Рим|Сад апельсинов': 'assets/images/places/rome-sad-apelsinov.jpg',
    'Рим|Холм Яникул': 'assets/images/places/rome-holm-yanikul.jpg',
    'Рим|Фонтан Треви ночью': 'assets/images/places/rome-fontan-trevi-nochyu.jpg',
    'Милан|Миланский собор': 'assets/images/places/milan-milanskiy-sobor.jpg',
    'Милан|Галерея Виктора Эммануила II': 'assets/images/places/milan-galereya-viktora-emmanuila-ii.jpg',
    'Милан|Театр Ла Скала': 'assets/images/places/milan-teatr-la-skala.jpg',
    'Милан|Каналы Навильи': 'assets/images/places/milan-kanaly-navili.jpg',
    'Милан|Парк Семпионе': 'assets/images/places/milan-park-sempione.jpg',
    'Милан|Озеро Комо рядом': 'assets/images/places/milan-ozero-komo-ryadom.jpg',
    'Венеция|Площадь Сан-Марко': 'assets/images/places/venice-ploschad-san-marko.jpg',
    'Венеция|Дворец дожей': 'assets/images/places/venice-dvorec-dozhey.jpg',
    'Венеция|Мост Риальто': 'assets/images/places/venice-most-rialto.jpg',
    'Венеция|Гранд-канал': 'assets/images/places/venice-grand-kanal.jpg',
    'Венеция|Остров Бурано': 'assets/images/places/venice-ostrov-burano.jpg',
    'Венеция|Лагуна Венеции на рассвете': 'assets/images/places/venice-laguna-venecii-na-rassvete.jpg',
    'Флоренция|Санта-Мария-дель-Фьоре': 'assets/images/places/florence-santa-mariya-del-fore.jpg',
    'Флоренция|Галерея Уффици': 'assets/images/places/florence-galereya-uffici.jpg',
    'Флоренция|Палаццо Веккьо': 'assets/images/places/florence-palacco-vekko.jpg',
    'Флоренция|Площадь Микеланджело': 'assets/images/places/florence-ploschad-mikelandzhelo.jpg',
    'Флоренция|Сады Боболи': 'assets/images/places/florence-sady-boboli.jpg',
    'Флоренция|Мост Понте-Веккьо': 'assets/images/places/florence-most-ponte-vekko.jpg',
    'Неаполь|Национальный археологический музей': 'assets/images/places/naples-nacionalnyy-arheologicheskiy-muzey.jpg',
    'Неаполь|Кастель-дель-Ово': 'assets/images/places/naples-kastel-del-ovo.jpg',
    'Неаполь|Подземный Неаполь': 'assets/images/places/naples-podzemnyy-neapol.jpg',
    'Неаполь|Вид на Везувий': 'assets/images/places/naples-vid-na-vezuviy.jpg',
    'Неаполь|Побережье Амальфи': 'assets/images/places/naples-poberezhe-amalfi.jpg',
    'Неаполь|Остров Капри': 'assets/images/places/naples-ostrov-kapri.jpg',
    'Париж|Эйфелева башня': 'assets/images/places/paris-eyfeleva-bashnya.jpg',
    'Париж|Лувр': 'assets/images/places/paris-luvr.jpg',
    'Париж|Собор Парижской Богоматери': 'assets/images/places/paris-sobor-parizhskoy-bogomateri.jpg',
    'Париж|Монмартр': 'assets/images/places/paris-monmartr.jpg',
    'Париж|Сад Тюильри': 'assets/images/places/paris-sad-tyuilri.jpg',
    'Париж|Набережные Сены': 'assets/images/places/paris-naberezhnye-seny.jpg',
    'Ницца|Английская набережная': 'assets/images/places/nice-angliyskaya-naberezhnaya.jpg',
    'Ницца|Старый город Ниццы': 'assets/images/places/nice-staryy-gorod-niccy.jpg',
    'Ницца|Музей Матисса': 'assets/images/places/nice-muzey-matissa.jpg',
    'Ницца|Замковый холм': 'assets/images/places/nice-zamkovyy-holm.jpg',
    'Ницца|Пляж Castel': 'assets/images/places/nice-plyazh-castel.jpg',
    'Ницца|Вильфранш-сюр-Мер': 'assets/images/places/nice-vilfransh-syur-mer.jpg',
    'Лион|Базилика Нотр-Дам-де-Фурвьер': 'assets/images/places/lyon-bazilika-notr-dam-de-furver.jpg',
    'Лион|Старый Лион': 'assets/images/places/lyon-staryy-lion.jpg',
    'Лион|Площадь Белькур': 'assets/images/places/lyon-ploschad-belkur.jpg',
    'Лион|Холм Фурвьер': 'assets/images/places/lyon-holm-furver.jpg',
    'Лион|Набережные Соны': 'assets/images/places/lyon-naberezhnye-sony.jpg',
    'Лион|Парк Тет д’Ор': 'assets/images/places/lyon-park-tet-d-or.jpg',
    'Марсель|Нотр-Дам-де-ла-Гард': 'assets/images/places/marseille-notr-dam-de-la-gard.jpg',
    'Марсель|Старый порт Марселя': 'assets/images/places/marseille-staryy-port-marselya.jpg',
    'Марсель|Музей MuCEM': 'assets/images/places/marseille-muzey-mucem.jpg',
    'Марсель|Каланки': 'assets/images/places/marseille-kalanki.jpg',
    'Марсель|Остров Иф': 'assets/images/places/marseille-ostrov-if.jpg',
    'Марсель|Пляж Прадо': 'assets/images/places/marseille-plyazh-prado.jpg',
    'Бангкок|Большой дворец': 'assets/images/places/bangkok-bolshoy-dvorec.jpg',
    'Бангкок|Храм Ват Арун': 'assets/images/places/bangkok-hram-vat-arun.jpg',
    'Бангкок|Храм Ват Пхо': 'assets/images/places/bangkok-hram-vat-pho.jpg',
    'Бангкок|Парк Люмпини': 'assets/images/places/bangkok-park-lyumpini.jpg',
    'Бангкок|Река Чао Прайя ночью': 'assets/images/places/bangkok-reka-chao-prayya-nochyu.jpg',
    'Бангкок|Рынок цветов Пак Клонг Талат': 'assets/images/places/bangkok-rynok-cvetov-pak-klong-talat.jpg',
    'Пхукет|Большой Будда Пхукета': 'assets/images/places/phuket-bolshoy-budda-phuketa.jpg',
    'Пхукет|Старый город Пхукета': 'assets/images/places/phuket-staryy-gorod-phuketa.jpg',
    'Пхукет|Храм Ват Чалонг': 'assets/images/places/phuket-hram-vat-chalong.jpg',
    'Пхукет|Пляж Най Харн': 'assets/images/places/phuket-plyazh-nay-harn.jpg',
    'Пхукет|Острова Пхи-Пхи': 'assets/images/places/phuket-ostrova-phi-phi.jpg',
    'Пхукет|Смотровая площадка Карон': 'assets/images/places/phuket-smotrovaya-ploschadka-karon.jpg',
    'Паттайя|Храм Истины': 'assets/images/places/pattaya-hram-istiny.jpg',
    'Паттайя|Nong Nooch Tropical Garden': 'assets/images/places/pattaya-nong-nooch-tropical-garden.jpg',
    'Паттайя|Большой Будда': 'assets/images/places/pattaya-bolshoy-budda.jpg',
    'Паттайя|Остров Ко Лан': 'assets/images/places/pattaya-ostrov-ko-lan.jpg',
    'Паттайя|Пляж Джомтьен': 'assets/images/places/pattaya-plyazh-dzhomten.jpg',
    'Паттайя|Смотровая Pattaya Viewpoint': 'assets/images/places/pattaya-smotrovaya-pattaya-viewpoint.jpg',
    'Чиангмай|Ват Пхра Тхат Дой Сутхеп': 'assets/images/places/chiang-mai-vat-phra-that-doy-suthep.jpg',
    'Чиангмай|Старый город Чиангмая': 'assets/images/places/chiang-mai-staryy-gorod-chiangmaya.jpg',
    'Чиангмай|Ват Чеди Луанг': 'assets/images/places/chiang-mai-vat-chedi-luang.jpg',
    'Чиангмай|Национальный парк Дой Интханон': 'assets/images/places/chiang-mai-nacionalnyy-park-doy-inthanon.jpg',
    'Чиангмай|Sticky Waterfalls': 'assets/images/places/chiang-mai-sticky-waterfalls.jpg',
    'Чиангмай|Рисовые поля Mae Rim': 'assets/images/places/chiang-mai-risovye-polya-mae-rim.jpg',
    'Самуи|Большой Будда Самуи': 'assets/images/places/samui-bolshoy-budda-samui.jpg',
    'Самуи|Wat Plai Laem': 'assets/images/places/samui-wat-plai-laem.jpg',
    'Самуи|Рыбацкая деревня Bophut': 'assets/images/places/samui-rybackaya-derevnya-bophut.jpg',
    'Самуи|Пляж Чавенг': 'assets/images/places/samui-plyazh-chaveng.jpg',
    'Самуи|Водопад На Муанг': 'assets/images/places/samui-vodopad-na-muang.jpg',
    'Самуи|Ang Thong Marine Park': 'assets/images/places/samui-ang-thong-marine-park.jpg',
    'Токио|Храм Сэнсо-дзи': 'assets/images/places/tokyo-hram-senso-dzi.jpg',
    'Токио|Токийская башня': 'assets/images/places/tokyo-tokiyskaya-bashnya.jpg',
    'Токио|Район Сибуя': 'assets/images/places/tokyo-rayon-sibuya.jpg',
    'Токио|Сады Синдзюку-гёэн': 'assets/images/places/tokyo-sady-sindzyuku-geen.jpg',
    'Токио|Река Мэгуро весной': 'assets/images/places/tokyo-reka-meguro-vesnoy.jpg',
    'Токио|Одайба вечером': 'assets/images/places/tokyo-odayba-vecherom.jpg',
    'Киото|Фусими Инари': 'assets/images/places/kyoto-fusimi-inari.jpg',
    'Киото|Кинкаку-дзи': 'assets/images/places/kyoto-kinkaku-dzi.jpg',
    'Киото|Киёмидзу-дэра': 'assets/images/places/kyoto-kiemidzu-dera.jpg',
    'Киото|Бамбуковая роща Арасияма': 'assets/images/places/kyoto-bambukovaya-roscha-arasiyama.jpg',
    'Киото|Философская тропа': 'assets/images/places/kyoto-filosofskaya-tropa.jpg',
    'Киото|Район Гион вечером': 'assets/images/places/kyoto-rayon-gion-vecherom.jpg',
    'Осака|Замок Осаки': 'assets/images/places/osaka-zamok-osaki.jpg',
    'Осака|Dotonbori': 'assets/images/places/osaka-dotonbori.jpg',
    'Осака|Universal Studios Japan': 'assets/images/places/osaka-universal-studios-japan.jpg',
    'Осака|Парк Наканосима': 'assets/images/places/osaka-park-nakanosima.jpg',
    'Осака|Tempozan Harbor Village': 'assets/images/places/osaka-tempozan-harbor-village.jpg',
    'Осака|Ночной Дотонбори': 'assets/images/places/osaka-nochnoy-dotonbori.jpg',
    'Саппоро|Часовая башня Саппоро': 'assets/images/places/sapporo-chasovaya-bashnya-sapporo.jpg',
    'Саппоро|Парк Одори': 'assets/images/places/sapporo-park-odori.jpg',
    'Саппоро|Музей пива Саппоро': 'assets/images/places/sapporo-muzey-piva-sapporo.jpg',
    'Саппоро|Гора Мойва': 'assets/images/places/sapporo-gora-moyva.jpg',
    'Саппоро|Парк Моэрэнума': 'assets/images/places/sapporo-park-moerenuma.jpg',
    'Саппоро|Горячие источники Дзёдзанкэй': 'assets/images/places/sapporo-goryachie-istochniki-dzedzankey.jpg',
    'Сеул|Дворец Кёнбоккун': 'assets/images/places/seoul-dvorec-kenbokkun.jpg',
    'Сеул|Башня N Seoul': 'assets/images/places/seoul-bashnya-n-seoul.jpg',
    'Сеул|Деревня Букчон Ханок': 'assets/images/places/seoul-derevnya-bukchon-hanok.jpg',
    'Сеул|Ручей Чхонгечхон': 'assets/images/places/seoul-ruchey-chhongechhon.jpg',
    'Сеул|Парк Ханган': 'assets/images/places/seoul-park-hangan.jpg',
    'Сеул|Гора Букхансан': 'assets/images/places/seoul-gora-bukhansan.jpg',
    'Пусан|Храм Хэдон Ёнгунса': 'assets/images/places/busan-hram-hedon-engunsa.jpg',
    'Пусан|Gamcheon Culture Village': 'assets/images/places/busan-gamcheon-culture-village.jpg',
    'Пусан|Рынок Jagalchi': 'assets/images/places/busan-rynok-jagalchi.jpg',
    'Пусан|Пляж Хэундэ': 'assets/images/places/busan-plyazh-heunde.jpg',
    'Пусан|Пляж Кваналли ночью': 'assets/images/places/busan-plyazh-kvanalli-nochyu.jpg',
    'Пусан|Остров Тонбэк': 'assets/images/places/busan-ostrov-tonbek.jpg',
    'Чеджу|Seongsan Ilchulbong': 'assets/images/places/jeju-seongsan-ilchulbong.jpg',
    'Чеджу|Музей чая O’sulloc': 'assets/images/places/jeju-muzey-chaya-o-sulloc.jpg',
    'Чеджу|Деревня Seongeup': 'assets/images/places/jeju-derevnya-seongeup.jpg',
    'Чеджу|Водопад Чонбан': 'assets/images/places/jeju-vodopad-chonban.jpg',
    'Чеджу|Пляж Хёпчже': 'assets/images/places/jeju-plyazh-hepchzhe.jpg',
    'Чеджу|Лавовые трубки Manjanggul': 'assets/images/places/jeju-lavovye-trubki-manjanggul.jpg',
    'Пекин|Запретный город': 'assets/images/places/beijing-zapretnyy-gorod.jpg',
    'Пекин|Храм Неба': 'assets/images/places/beijing-hram-neba.jpg',
    'Пекин|Летний дворец': 'assets/images/places/beijing-letniy-dvorec.jpg',
    'Пекин|Великая Китайская стена Бадалин': 'assets/images/places/beijing-velikaya-kitayskaya-stena-badalin.jpg',
    'Пекин|Парк Бэйхай': 'assets/images/places/beijing-park-beyhay.jpg',
    'Пекин|Озеро Хоухай': 'assets/images/places/beijing-ozero-houhay.jpg',
    'Шанхай|Набережная Вайтань': 'assets/images/places/shanghai-naberezhnaya-vaytan.jpg',
    'Шанхай|Сад Юйюань': 'assets/images/places/shanghai-sad-yuyyuan.jpg',
    'Шанхай|Шанхайская башня': 'assets/images/places/shanghai-shanhayskaya-bashnya.jpg',
    'Шанхай|Район Пудун ночью': 'assets/images/places/shanghai-rayon-pudun-nochyu.jpg',
    'Шанхай|Французская концессия': 'assets/images/places/shanghai-francuzskaya-koncessiya.jpg',
    'Шанхай|Парк Century': 'assets/images/places/shanghai-park-century.jpg',
    'Гуанчжоу|Canton Tower': 'assets/images/places/guangzhou-canton-tower.jpg',
    'Гуанчжоу|Храм Шести баньяновых деревьев': 'assets/images/places/guangzhou-hram-shesti-banyanovyh-derevev.jpg',
    'Гуанчжоу|Chen Clan Ancestral Hall': 'assets/images/places/guangzhou-chen-clan-ancestral-hall.jpg',
    'Гуанчжоу|Остров Шамянь': 'assets/images/places/guangzhou-ostrov-shamyan.jpg',
    'Гуанчжоу|Парк Юэсю': 'assets/images/places/guangzhou-park-yuesyu.jpg',
    'Гуанчжоу|Жемчужная река вечером': 'assets/images/places/guangzhou-zhemchuzhnaya-reka-vecherom.jpg',
    'Гонконг|Пик Виктория': 'assets/images/places/hong-kong-pik-viktoriya.jpg',
    'Гонконг|Большой Будда Тяньтань': 'assets/images/places/hong-kong-bolshoy-budda-tyantan.jpg',
    'Гонконг|Аллея звёзд': 'assets/images/places/hong-kong-alleya-zvezd.jpg',
    'Гонконг|Бухта Виктория': 'assets/images/places/hong-kong-buhta-viktoriya.jpg',
    'Гонконг|Dragon’s Back Trail': 'assets/images/places/hong-kong-dragon-s-back-trail.jpg',
    'Гонконг|Пляж Repulse Bay': 'assets/images/places/hong-kong-plyazh-repulse-bay.jpg',
    'Нью-Йорк|Статуя Свободы': 'assets/images/places/new-york-statuya-svobody.jpg',
    'Нью-Йорк|Метрополитен-музей': 'assets/images/places/new-york-metropoliten-muzey.jpg',
    'Нью-Йорк|Таймс-сквер': 'assets/images/places/new-york-tayms-skver.jpg',
    'Нью-Йорк|Центральный парк': 'assets/images/places/new-york-centralnyy-park.jpg',
    'Нью-Йорк|Бруклинский мост': 'assets/images/places/new-york-bruklinskiy-most.jpg',
    'Нью-Йорк|High Line': 'assets/images/places/new-york-high-line.jpg',
    'Лос-Анджелес|Голливудская аллея славы': 'assets/images/places/los-angeles-gollivudskaya-alleya-slavy.jpg',
    'Лос-Анджелес|Griffith Observatory': 'assets/images/places/los-angeles-griffith-observatory.jpg',
    'Лос-Анджелес|Getty Center': 'assets/images/places/los-angeles-getty-center.jpg',
    'Лос-Анджелес|Пляж Санта-Моника': 'assets/images/places/los-angeles-plyazh-santa-monika.jpg',
    'Лос-Анджелес|Runyon Canyon': 'assets/images/places/los-angeles-runyon-canyon.jpg',
    'Лос-Анджелес|Venice Canals': 'assets/images/places/los-angeles-venice-canals.jpg',
    'Майами|Art Deco Historic District': 'assets/images/places/mayami-art-deco-historic-district.jpg',
    'Майами|Vizcaya Museum and Gardens': 'assets/images/places/mayami-vizcaya-museum-and-gardens.jpg',
    'Майами|Little Havana': 'assets/images/places/mayami-little-havana.jpg',
    'Майами|South Beach': 'assets/images/places/mayami-south-beach.jpg',
    'Майами|Key Biscayne': 'assets/images/places/mayami-key-biscayne.jpg',
    'Майами|Wynwood Walls вечером': 'assets/images/places/mayami-wynwood-walls-vecherom.jpg',
    'Лас-Вегас|Las Vegas Strip': 'assets/images/places/las-vegas-las-vegas-strip.jpg',
    'Лас-Вегас|Bellagio Fountains': 'assets/images/places/las-vegas-bellagio-fountains.jpg',
    'Лас-Вегас|Fremont Street Experience': 'assets/images/places/las-vegas-fremont-street-experience.jpg',
    'Лас-Вегас|Red Rock Canyon': 'assets/images/places/las-vegas-red-rock-canyon.jpg',
    'Лас-Вегас|Valley of Fire': 'assets/images/places/las-vegas-valley-of-fire.jpg',
    'Лас-Вегас|Смотровая High Roller': 'assets/images/places/las-vegas-smotrovaya-high-roller.jpg',
    'Сан-Франциско|Golden Gate Bridge': 'assets/images/places/san-francisco-golden-gate-bridge.jpg',
    'Сан-Франциско|Остров Алькатрас': 'assets/images/places/san-francisco-ostrov-alkatras.jpg',
    'Сан-Франциско|Fisherman’s Wharf': 'assets/images/places/san-francisco-fisherman-s-wharf.jpg',
    'Сан-Франциско|Twin Peaks': 'assets/images/places/san-francisco-twin-peaks.jpg',
    'Сан-Франциско|Lands End': 'assets/images/places/san-francisco-lands-end.jpg',
    'Сан-Франциско|Baker Beach': 'assets/images/places/san-francisco-baker-beach.jpg',
    'Лондон|Британский музей': 'assets/images/places/london-britanskiy-muzey.jpg',
    'Лондон|Тауэр': 'assets/images/places/london-tauer.jpg',
    'Лондон|Букингемский дворец': 'assets/images/places/london-bukingemskiy-dvorec.jpg',
    'Лондон|Скай Гарден': 'assets/images/places/london-skay-garden.jpg',
    'Лондон|Гайд-парк': 'assets/images/places/london-gayd-park.jpg',
    'Лондон|Набережная Темзы вечером': 'assets/images/places/london-naberezhnaya-temzy-vecherom.jpg',
    'Эдинбург|Эдинбургский замок': 'assets/images/places/edinburgh-edinburgskiy-zamok.jpg',
    'Эдинбург|Королевская миля': 'assets/images/places/edinburgh-korolevskaya-milya.jpg',
    'Эдинбург|Дворец Холирудхаус': 'assets/images/places/edinburgh-dvorec-holirudhaus.jpg',
    'Эдинбург|Arthur’s Seat': 'assets/images/places/edinburgh-arthur-s-seat.jpg',
    'Эдинбург|Calton Hill': 'assets/images/places/edinburgh-calton-hill.jpg',
    'Эдинбург|Dean Village': 'assets/images/places/edinburgh-dean-village.jpg',
    'Манчестер|Manchester Cathedral': 'assets/images/places/manchester-manchester-cathedral.jpg',
    'Манчестер|Science and Industry Museum': 'assets/images/places/manchester-science-and-industry-museum.jpg',
    'Манчестер|John Rylands Library': 'assets/images/places/manchester-john-rylands-library.jpg',
    'Манчестер|Castlefield Canals': 'assets/images/places/manchester-castlefield-canals.jpg',
    'Манчестер|Heaton Park': 'assets/images/places/manchester-heaton-park.jpg',
    'Манчестер|Salford Quays': 'assets/images/places/manchester-salford-quays.jpg',
    'Берлин|Бранденбургские ворота': 'assets/images/places/berlin-brandenburgskie-vorota.jpg',
    'Берлин|Рейхстаг': 'assets/images/places/berlin-reyhstag.jpg',
    'Берлин|Музейный остров': 'assets/images/places/berlin-muzeynyy-ostrov.jpg',
    'Берлин|Тиргартен': 'assets/images/places/berlin-tirgarten.jpg',
    'Берлин|East Side Gallery': 'assets/images/places/berlin-east-side-gallery.jpg',
    'Берлин|Темпельхофское поле': 'assets/images/places/berlin-tempelhofskoe-pole.jpg',
    'Мюнхен|Мариенплац': 'assets/images/places/munich-marienplac.jpg',
    'Мюнхен|Дворец Нимфенбург': 'assets/images/places/munich-dvorec-nimfenburg.jpg',
    'Мюнхен|Мюнхенская резиденция': 'assets/images/places/munich-myunhenskaya-rezidenciya.jpg',
    'Мюнхен|Английский сад': 'assets/images/places/munich-angliyskiy-sad.jpg',
    'Мюнхен|Олимпийский парк': 'assets/images/places/munich-olimpiyskiy-park.jpg',
    'Мюнхен|Озеро Штарнберг': 'assets/images/places/munich-ozero-shtarnberg.jpg',
    'Гамбург|Эльбская филармония': 'assets/images/places/hamburg-elbskaya-filarmoniya.jpg',
    'Гамбург|Миниатюрная страна чудес': 'assets/images/places/hamburg-miniatyurnaya-strana-chudes.jpg',
    'Гамбург|Ратуша Гамбурга': 'assets/images/places/hamburg-ratusha-gamburga.jpg',
    'Гамбург|Озеро Альстер': 'assets/images/places/hamburg-ozero-alster.jpg',
    'Гамбург|Шпайхерштадт': 'assets/images/places/hamburg-shpayhershtadt.jpg',
    'Гамбург|Парк Planten un Blomen': 'assets/images/places/hamburg-park-planten-un-blomen.jpg',
    'Афины|Афинский Акрополь': 'assets/images/places/athens-afinskiy-akropol.jpg',
    'Афины|Музей Акрополя': 'assets/images/places/athens-muzey-akropolya.jpg',
    'Афины|Агора Афин': 'assets/images/places/athens-agora-afin.jpg',
    'Афины|Холм Ликавит': 'assets/images/places/athens-holm-likavit.jpg',
    'Афины|Район Плака': 'assets/images/places/athens-rayon-plaka.jpg',
    'Афины|Мыс Сунион': 'assets/images/places/athens-mys-sunion.jpg',
    'Санторини|Деревня Ия': 'assets/images/places/santorini-derevnya-iya.jpg',
    'Санторини|Археологический объект Акротири': 'assets/images/places/santorini-arheologicheskiy-obekt-akrotiri.jpg',
    'Санторини|Фира': 'assets/images/places/santorini-fira.jpg',
    'Санторини|Кальдера Санторини': 'assets/images/places/santorini-kaldera-santorini.jpg',
    'Санторини|Красный пляж': 'assets/images/places/santorini-krasnyy-plyazh.jpg',
    'Санторини|Закат в Ие': 'assets/images/places/santorini-zakat-v-ie.jpg',
    'Крит|Кносский дворец': 'assets/images/places/crete-knosskiy-dvorec.jpg',
    'Крит|Старый город Ханьи': 'assets/images/places/crete-staryy-gorod-hani.jpg',
    'Крит|Крепость Кулес': 'assets/images/places/crete-krepost-kules.jpg',
    'Крит|Лагуна Балос': 'assets/images/places/crete-laguna-balos.jpg',
    'Крит|Пляж Элафониси': 'assets/images/places/crete-plyazh-elafonisi.jpg',
    'Крит|Самарийское ущелье': 'assets/images/places/crete-samariyskoe-uschele.jpg',
    'Салоники|Белая башня': 'assets/images/places/thessaloniki-belaya-bashnya.jpg',
    'Салоники|Ротонда Галерия': 'assets/images/places/thessaloniki-rotonda-galeriya.jpg',
    'Салоники|Арка Галерия': 'assets/images/places/thessaloniki-arka-galeriya.jpg',
    'Салоники|Набережная Салоник': 'assets/images/places/thessaloniki-naberezhnaya-salonik.jpg',
    'Салоники|Верхний город Ано Поли': 'assets/images/places/thessaloniki-verhniy-gorod-ano-poli.jpg',
    'Салоники|Озеро Керкини': 'assets/images/places/thessaloniki-ozero-kerkini.jpg',
    'Каир|Пирамиды Гизы': 'assets/images/places/cairo-piramidy-gizy.jpg',
    'Каир|Египетский музей': 'assets/images/places/cairo-egipetskiy-muzey.jpg',
    'Каир|Цитадель Саладина': 'assets/images/places/cairo-citadel-saladina.jpg',
    'Каир|Нил вечером': 'assets/images/places/cairo-nil-vecherom.jpg',
    'Каир|Парк Аль-Азхар': 'assets/images/places/cairo-park-al-azhar.jpg',
    'Каир|Хан эль-Халили ночью': 'assets/images/places/cairo-han-el-halili-nochyu.jpg',
    'Шарм-эль-Шейх|Старый рынок Шарм-эль-Шейха': 'assets/images/places/sharm-el-sheikh-staryy-rynok-sharm-el-sheyha.jpg',
    'Шарм-эль-Шейх|Площадь Сохо': 'assets/images/places/sharm-el-sheikh-ploschad-soho.jpg',
    'Шарм-эль-Шейх|Мечеть Аль-Сахаба': 'assets/images/places/sharm-el-sheikh-mechet-al-sahaba.jpg',
    'Шарм-эль-Шейх|Национальный парк Рас-Мохаммед': 'assets/images/places/sharm-el-sheikh-nacionalnyy-park-ras-mohammed.jpg',
    'Шарм-эль-Шейх|Бухта Наама': 'assets/images/places/sharm-el-sheikh-buhta-naama.jpg',
    'Шарм-эль-Шейх|Голубая дыра Дахаба': 'assets/images/places/sharm-el-sheikh-golubaya-dyra-dahaba.jpg',
    'Хургада|Hurghada Marina': 'assets/images/places/hurghada-hurghada-marina.jpg',
    'Хургада|Sand City Hurghada': 'assets/images/places/hurghada-sand-city-hurghada.jpg',
    'Хургада|Мечеть Эль-Мина': 'assets/images/places/hurghada-mechet-el-mina.jpg',
    'Хургада|Острова Гифтун': 'assets/images/places/hurghada-ostrova-giftun.jpg',
    'Хургада|Пляж Mahmya': 'assets/images/places/hurghada-plyazh-mahmya.jpg',
    'Хургада|Пустынное сафари на закате': 'assets/images/places/hurghada-pustynnoe-safari-na-zakate.jpg',
    'Александрия|Библиотека Александрина': 'assets/images/places/alexandria-biblioteka-aleksandrina.jpg',
    'Александрия|Цитадель Кайт-Бей': 'assets/images/places/alexandria-citadel-kayt-bey.jpg',
    'Александрия|Катакомбы Ком-эль-Шукафа': 'assets/images/places/alexandria-katakomby-kom-el-shukafa.jpg',
    'Александрия|Набережная Корниш': 'assets/images/places/alexandria-naberezhnaya-kornish.jpg',
    'Александрия|Дворец Монтаза': 'assets/images/places/alexandria-dvorec-montaza.jpg',
    'Александрия|Средиземноморские пляжи': 'assets/images/places/alexandria-sredizemnomorskie-plyazhi.jpg',
    'Ташкент|Комплекс Хаст-Имам': 'assets/images/places/tashkent-kompleks-hast-imam.jpg',
    'Ташкент|Рынок Чорсу': 'assets/images/places/tashkent-rynok-chorsu.jpg',
    'Ташкент|Музей Амира Тимура': 'assets/images/places/tashkent-muzey-amira-timura.jpg',
    'Ташкент|Ташкентская телебашня вечером': 'assets/images/places/tashkent-tashkentskaya-telebashnya-vecherom.jpg',
    'Ташкент|Японский сад': 'assets/images/places/tashkent-yaponskiy-sad.jpg',
    'Ташкент|Парк Анхор': 'assets/images/places/tashkent-park-anhor.jpg',
    'Самарканд|Регистан': 'assets/images/places/samarkand-registan.jpg',
    'Самарканд|Шахи-Зинда': 'assets/images/places/samarkand-shahi-zinda.jpg',
    'Самарканд|Мавзолей Гур-Эмир': 'assets/images/places/samarkand-mavzoley-gur-emir.jpg',
    'Самарканд|Сиабский базар на рассвете': 'assets/images/places/samarkand-siabskiy-bazar-na-rassvete.jpg',
    'Самарканд|Обсерватория Улугбека': 'assets/images/places/samarkand-observatoriya-ulugbeka.jpg',
    'Самарканд|Сады Самарканда': 'assets/images/places/samarkand-sady-samarkanda.jpg',
    'Бухара|Пои-Калян': 'assets/images/places/bukhara-poi-kalyan.jpg',
    'Бухара|Крепость Арк': 'assets/images/places/bukhara-krepost-ark.jpg',
    'Бухара|Ляби-Хауз': 'assets/images/places/bukhara-lyabi-hauz.jpg',
    'Бухара|Старый город Бухары': 'assets/images/places/bukhara-staryy-gorod-buhary.jpg',
    'Бухара|Чор-Минор': 'assets/images/places/bukhara-chor-minor.jpg',
    'Бухара|Караванные улочки вечером': 'assets/images/places/bukhara-karavannye-ulochki-vecherom.jpg'
};

// Если основной объект TP_IMAGE_OVERRIDES уже существует, сразу добавляем туда эти пути.
if (typeof TP_IMAGE_OVERRIDES !== 'undefined' && TP_IMAGE_OVERRIDES.places) {
  Object.assign(TP_IMAGE_OVERRIDES.places, PLACE_IMAGE_OVERRIDES);
}
